
import winter from '../assets/events/winter1.jpg'
import winterBack from '../assets/events/winterBack.jpg'
import woc1 from '../assets/events/backside/woc1.jpg'
import woc2 from '../assets/events/backside/woc2.jpg'
import woc3 from '../assets/events/backside/woc3.jpg'
import woc4 from '../assets/events/backside/woc4.jpg'
const eventData = [
    {
        id:1,
        upcoming:true,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:2,
        upcoming:true,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:3,
        upcoming:true,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:4,
        upcoming:true,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:5,
        upcoming:true,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:6,
        upcoming:false,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:7,
        upcoming:false,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:8,
        upcoming:false,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:9,
        upcoming:false,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
    {
        id:10,
        upcoming:false,
        frontBg: `url(${winter})`,
        titleFrontTop: "WinterHacks",
        titleFrontBottom: "Ideathon",
        titleFrontColor: "#00021c",
        backColor:"white",
        descBack: "WinterHacks is an ideathon to inspire students about GSOC",
        backAlbum:[woc1,woc2,woc3,woc4],
        date: "10 Nov, 2023",
        time:"10am-7pm",
        venue:"DJ Seminar Hall",
        link:"https://unstop.com/competitions/gdsc-winter-hacks-shri-vile-parle-kelavani-mandals-dwarkadas-j-sanghvi-college-of-engineering-djsce-mumbai-802133",
        backBg: `url(${winterBack})`,        
    },
]

export default eventData;